# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/program_4k/project_1_base_v3.00_2018/project_1_base.srcs/sources_1/ip/ila_2/ila_2.xci
# IP: The module: 'ila_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/program_4k/project_1_base_v3.00_2018/project_1_base.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/program_4k/project_1_base_v3.00_2018/project_1_base.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/program_4k/project_1_base_v3.00_2018/project_1_base.srcs/sources_1/ip/ila_2/ila_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/program_4k/project_1_base_v3.00_2018/project_1_base.srcs/sources_1/ip/ila_2/ila_2.xci
# IP: The module: 'ila_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/program_4k/project_1_base_v3.00_2018/project_1_base.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/program_4k/project_1_base_v3.00_2018/project_1_base.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/program_4k/project_1_base_v3.00_2018/project_1_base.srcs/sources_1/ip/ila_2/ila_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
